# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gui1(object):
    def setupUi(self, gui1):
        gui1.setObjectName("gui1")
        gui1.resize(1239, 833)
        self.centralwidget = QtWidgets.QWidget(gui1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1241, 841))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\DELL\\AppData\\Roaming\\Python\\Python39\\Scripts\\Jarvis_Gui (2).gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 360, 361, 231))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\DELL\\AppData\\Roaming\\Python\Python39\\Scripts\\Iron_Template_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1070, 360, 93, 41))
        self.pushButton.setStyleSheet("background-color: rgb(235, 255, 10);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1070, 430, 93, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(243, 255, 3);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        gui1.setCentralWidget(self.centralwidget)

        self.retranslateUi(gui1)
        QtCore.QMetaObject.connectSlotsByName(gui1)

    def retranslateUi(self, gui1):
        _translate = QtCore.QCoreApplication.translate
        gui1.setWindowTitle(_translate("gui1", "MainWindow"))
        self.pushButton.setText(_translate("gui1", "START"))
        self.pushButton_2.setText(_translate("gui1", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gui1 = QtWidgets.QMainWindow()
    ui = Ui_gui1()
    ui.setupUi(gui1)
    gui1.show()
    sys.exit(app.exec_())
